export const CATEGORIES = [
  { id: 53, name: 'Traditional Rice & Millets', count: 26, description: 'Direct from the finest farms', image: '/ai_images/organic_grains_1776231059575.png' },
  { id: 61, name: 'Flour & Powders', count: 14, description: 'Traditional stone-ground purity', image: '/ai_images/indian_spices_1776231045209.png' },
  { id: 70, name: 'Cold Pressed Oils', count: 48, description: 'Traditional wood-pressed goodness', image: '/ai_images/organic_oils_banner.png' },
  { id: 76, name: 'Pickles & Thokku', count: 20, description: 'Authentic grandma recipes', image: '/ai_images/mango_ginger_pickle.png' },
  { id: 83, name: 'Homemade Snacks', count: 16, description: 'Crispy and delicious local treats', image: '/ai_images/murukku_premium.png' },
  { id: 90, name: 'Cookies & Cakes', count: 35, description: 'Healthy whole-grain baked treats', image: '/ai_images/mysore_pak_brass.png' },
  { id: 97, name: 'Dry Fruits & Nuts', count: 12, description: 'Premium selection of healthy nuts', image: '/ai_images/honey_gold_1776231080758.png' },
  { id: 104, name: 'Natural Products', count: 15, description: 'Herbal and natural body care essentials', image: '/ai_images/organic_grains_1776231059575.png' },
  { id: 111, name: 'Quick Cook Mixes', count: 22, description: 'Instant, healthy traditional food mixes', image: '/ai_images/organic_grains_1776231059575.png' },
];

export const HOME_BANNERS = [
  { id: 1, image: '/ai_images/banner_farm_fresh.png', title: 'Farm Fresh Delivered to You', subtitle: '🌿 Just Producted Today', cta: 'Shop Fresh', link: '/products?category=Traditional Rice & Millets' },
  { id: 2, image: '/ai_images/banner_heritage_spices.png', title: 'Stone Ground Authentic Spices', subtitle: '🌶️ Secret of South Indian Taste', cta: 'Explore Spices', link: '/products?category=Flour & Powders' },
  { id: 3, image: '/ai_images/banner_natural_products.png', title: 'Cold Pressed Pure Oils', subtitle: '🫒 Health in Every Drop', cta: 'Shop Oils', link: '/products?category=Cold Pressed Oils' },
];


export const BRANDS = [
  {
    id: 37,
    name: 'Namma Nature',
    tagline: 'Purely natural, purely yours',
    description: 'Founded in 2015, Namma Nature sources directly from certified organic farms across Tamil Nadu and Karnataka. Every product is lab-tested, preservative-free and packed with traditional goodness.',
    logo: '/ai_images/indian_spices_1776231045209.png',
    productCount: 34,
    category: 'Grains, Spices & Snacks',
    badge: 'Certified Organic',
    color: '#065f46'
  },
  {
    id: 38,
    name: 'Grama Fresh',
    tagline: 'Straight from the heart of the village',
    description: 'Grama Fresh partners with over 200 small-scale farmers across rural India to bring you cold-pressed oils, fresh dairy, and artisan sweets — made in time-honoured ways with zero additives.',
    logo: '/ai_images/organic_grains_1776231059575.png',
    productCount: 22,
    category: 'Oils, Dairy & Sweets',
    badge: 'Village Sourced',
    color: '#d97706'
  },
  {
    id: 39,
    name: 'Kovil Kalai',
    tagline: 'Sacred recipes, Story flavours',
    description: 'Kovil Kalai specialises in temple-style ritual ingredients, traditional sweet meats, and festival spice blends — all hand-processed by artisan communities.',
    logo: '/ai_images/cinematic_farm_1776230966841.png',
    productCount: 18,
    category: 'Spices & Sweets',
    badge: 'Story Brand',
    color: '#7c3aed'
  },
];

export const PRODUCTS = [
  {
    id: 1,
    name: 'Premium Toor Dal',
    category: 'Grains & Pulses',
    brand: 'Namma Nature',
    price: 180,
    originalPrice: 220,
    image: 'https://s3.ap-south-1.amazonaws.com/namma-orru-foods/products/1777019972674-millet_noodles.png',
    rating: 4.8,
    reviews: 124,
    tags: ['best-selling', 'organic-special'],
    description: 'Our Toor Dal is sourced directly from organic farms in Andhra Pradesh. It is hulled and split to retain maximum nutrition. Rich in protein and dietary fibre, it cooks quickly and has a naturally earthy flavour perfect for dal tadka and sambhar.',
    variants: [
      { id: 1, name: '500g', price: 95 },
      { id: 2, name: '1kg', price: 180 },
      { id: 3, name: '5kg', price: 850 },
    ],
    highlights: ['100% Organic', 'High Protein (22g/100g)', 'No Preservatives', 'Direct Farm Sourcing']
  },
  {
    id: 2,
    name: 'Cold Pressed Peanut Oil',
    category: 'Organic Oils',
    brand: 'Grama Fresh',
    price: 320,
    originalPrice: 399,
    image: 'https://s3.ap-south-1.amazonaws.com/namma-orru-foods/products/1777019971640-traditional_oil.png',
    rating: 4.9,
    reviews: 85,
    tags: ['best-selling', 'organic-special'],
    description: 'Traditional wood-pressed groundnut oil extracted at low temperature to preserve its natural nutrients, aroma, and golden colour. No hexane. No refining. No trans fats. Just the pure essence of Indian groundnuts.',
    variants: [
      { id: 4, name: '1L', price: 320 },
      { id: 5, name: '5L', price: 1550 },
    ],
    highlights: ['Wood Pressed', 'Rich Natural Aroma', 'Cholesterol Free', 'No Hexane or Refining']
  },
  {
    id: 3,
    name: 'Aromatic Red Chilli Powder',
    category: 'Authentic Spices',
    brand: 'Namma Nature',
    price: 120,
    originalPrice: 150,
    image: 'https://s3.ap-south-1.amazonaws.com/namma-orru-foods/products/1777019972496-tomato_sauce.png',
    rating: 4.7,
    reviews: 210,
    tags: ['best-selling'],
    description: 'Made from sun-dried Guntur and Byadagi chillies, stone-ground to a fine powder. No artificial colour or synthetic flavour enhancers — the vibrant red colour and fiery flavour are entirely natural.',
    variants: [
      { id: 6, name: '100g', price: 60 },
      { id: 7, name: '250g', price: 120 },
      { id: 8, name: '500g', price: 220 },
    ],
    highlights: ['Stone Ground', 'No Artificial Colour', 'Guntur & Byadagi Blend', 'Intense Flavour']
  },
  {
    id: 4,
    name: 'Traditional A2 Ghee',
    category: 'Dairy Products',
    brand: 'Grama Fresh',
    price: 650,
    originalPrice: 799,
    image: 'https://s3.ap-south-1.amazonaws.com/namma-orru-foods/images/46768afb020c4f6ffa57da4aa6c47f0c-ChatGPT Image Apr 24, 2026, 08_22_07 AM.png',
    rating: 4.9,
    reviews: 312,
    tags: ['best-selling', 'organic-special'],
    description: 'Bilona method A2 cow ghee, crafted in small batches by local dairy families. Milk is curd-set, hand-churned, and the butter is slowly simmered to produce a rich, nutty ghee with a golden hue. Aids digestion and is ideal for cooking, as a spread or in Ayurvedic rituals.',
    variants: [
      { id: 9, name: '250ml', price: 350 },
      { id: 10, name: '500ml', price: 650 },
      { id: 11, name: '1L', price: 1250 },
    ],
    highlights: ['A2 Cow Milk', 'Bilona Method', 'Rich in Butyric Acid', 'Lactose Free']
  },
  {
    id: 5,
    name: 'Handmade Murukku',
    category: 'Indian Snacks',
    brand: 'Namma Nature',
    price: 85,
    originalPrice: 110,
    image: 'https://s3.ap-south-1.amazonaws.com/namma-orru-foods/images/9582bb3c5558ab879e66cdc2574a0108-ChatGPT Image Apr 24, 2026, 08_46_09 AM.png',
    rating: 4.6,
    reviews: 96,
    tags: ['best-selling'],
    description: 'Classic spiral murukku hand-made using rice flour, urad dal and sesame seeds. Fried in fresh cold-pressed oil for the crunchy, melt-in-mouth texture your grandparents loved. A beloved South Indian tea-time snack.',
    variants: [
      { id: 12, name: '200g', price: 85 },
      { id: 13, name: '500g', price: 200 },
    ],
    highlights: ['Handmade', 'No Maida', 'Fried in Cold-Pressed Oil', 'Traditional Recipe']
  },
  {
    id: 6,
    name: 'Fresh Jaggery Blocks',
    category: 'Local Sweets',
    brand: 'Grama Fresh',
    price: 110,
    originalPrice: 140,
    image: 'https://s3.ap-south-1.amazonaws.com/namma-orru-foods/images/46768afb020c4f6ffa57da4aa6c47f0c-ChatGPT Image Apr 24, 2026, 08_22_07 AM.png',
    rating: 4.8,
    reviews: 153,
    tags: ['organic-special'],
    description: 'Unrefined pure sugarcane jaggery blocks sourced from Kolhapur, one of India\'s finest jaggery belts. No lime, no sulphur, no adulterants — only the purest concentration of sugarcane juice, boiled in open iron pans over wood fire.',
    variants: [
      { id: 14, name: '500g', price: 110 },
      { id: 15, name: '1kg', price: 210 },
      { id: 16, name: '2kg', price: 400 },
    ],
    highlights: ['Zero Sulphur', 'Rich in Iron & Minerals', 'No Artificial Sweeteners', 'Kolhapur Sourced']
  },
  {
    id: 7,
    name: 'Wild Forest Honey',
    category: 'Dairy Products',
    brand: 'Namma Nature',
    price: 399,
    originalPrice: 499,
    image: 'https://s3.ap-south-1.amazonaws.com/namma-orru-foods/images/46768afb020c4f6ffa57da4aa6c47f0c-ChatGPT Image Apr 24, 2026, 08_22_07 AM.png',
    rating: 4.9,
    reviews: 287,
    tags: ['best-selling', 'organic-special'],
    description: 'Raw, unprocessed wild honey collected from the rock bee hives in the forests of Western Ghats. No heating, no filtration, no sugar. Rich in natural enzymes, pollen and propolis. Dark amber colour with an intense floral aroma.',
    variants: [
      { id: 17, name: '250g', price: 250 },
      { id: 18, name: '500g', price: 399 },
      { id: 19, name: '1kg', price: 750 },
    ],
    highlights: ['Raw & Unprocessed', 'Western Ghats Origin', 'Rich in Enzymes', 'No Added Sugar']
  },
  {
    id: 8,
    name: 'Organic Basmati Rice',
    category: 'Grains & Pulses',
    brand: 'Grama Fresh',
    price: 299,
    originalPrice: 380,
    image: 'https://s3.ap-south-1.amazonaws.com/namma-orru-foods/products/1777019972674-millet_noodles.png',
    rating: 4.7,
    reviews: 198,
    tags: ['best-selling', 'organic-special'],
    description: 'Premium aged basmati rice from the foothills of Himalayas. Naturally aromatic, extra-long grain that stays fluffy and separate after cooking. Aged for 12 months for enhanced fragrance and texture.',
    variants: [
      { id: 20, name: '1kg', price: 299 },
      { id: 21, name: '5kg', price: 1399 },
      { id: 22, name: '10kg', price: 2699 },
    ],
    highlights: ['12-Month Aged', 'Extra Long Grain', 'Himalayan Origin', 'Pesticide Free']
  },
  {
    id: 9,
    name: 'Organic Turmeric Powder',
    category: 'Authentic Spices',
    brand: 'Kovil Kalai',
    price: 95,
    originalPrice: 130,
    image: 'https://s3.ap-south-1.amazonaws.com/namma-orru-foods/images/94fd90e209da1c702b26b8943940f17f-ChatGPT Image Apr 24, 2026, 08_22_24 AM.png',
    rating: 4.8,
    reviews: 176,
    tags: ['organic-special'],
    description: 'Traditional Erode turmeric, sun-dried and stone-ground to preserve its high curcumin content (7%+). Vibrant golden-yellow colour with a warm, earthy aroma. Used in cooking, milk drinks, and Ayurvedic remedies.',
    variants: [
      { id: 23, name: '100g', price: 50 },
      { id: 24, name: '250g', price: 95 },
      { id: 25, name: '500g', price: 180 },
    ],
    highlights: ['7%+ Curcumin', 'Erode Origin', 'Stone Ground', 'Anti-inflammatory']
  },
  {
    id: 10,
    name: 'Cold Pressed Coconut Oil',
    category: 'Organic Oils',
    brand: 'Grama Fresh',
    price: 280,
    originalPrice: 350,
    image: 'https://s3.ap-south-1.amazonaws.com/namma-orru-foods/products/1777019971640-traditional_oil.png',
    rating: 4.9,
    reviews: 245,
    tags: ['best-selling', 'organic-special'],
    description: 'Virgin coconut oil extracted from fresh coconut meat using the traditional wooden chekku method. Retains lauric acid, MCTs (medium chain triglycerides) and natural coconut aroma. Ideal for cooking, skin and hair care.',
    variants: [
      { id: 26, name: '500ml', price: 280 },
      { id: 27, name: '1L', price: 520 },
      { id: 28, name: '5L', price: 2400 },
    ],
    highlights: ['Virgin & Unrefined', 'Chekku Pressed', 'Rich in Lauric Acid', 'Multi-purpose']
  },
  {
    id: 11,
    name: 'Ragi Malt Powder',
    category: 'Grains & Pulses',
    brand: 'Namma Nature',
    price: 145,
    originalPrice: 180,
    image: '/ai_images/cinematic_farm_1776230966841.png',
    rating: 4.6,
    reviews: 112,
    tags: ['organic-special'],
    description: 'Sprouted ragi (finger millet) malt powder, roasted to perfection and enriched with cardamom and dry ginger. Rich in calcium, iron and amino acids. Perfect as a healthy breakfast drink when mixed with warm milk.',
    variants: [
      { id: 29, name: '200g', price: 85 },
      { id: 30, name: '500g', price: 145 },
      { id: 31, name: '1kg', price: 270 },
    ],
    highlights: ['Sprouted Ragi', 'Rich in Calcium', 'No Preservatives', 'Breakfast Ready']
  },
  {
    id: 12,
    name: 'Organic Black Pepper',
    category: 'Authentic Spices',
    brand: 'Kovil Kalai',
    price: 185,
    originalPrice: 240,
    image: '/ai_images/honey_gold_1776231080758.png',
    rating: 4.8,
    reviews: 89,
    tags: ['best-selling', 'organic-special'],
    description: 'Premium Wayanad black pepper, sun-dried to lock in the essential oils and piperine. Bold, pungent flavour with a complex aroma. Hand-picked from organic pepper vines grown under natural shade.',
    variants: [
      { id: 32, name: '50g', price: 95 },
      { id: 33, name: '100g', price: 185 },
      { id: 34, name: '250g', price: 420 },
    ],
    highlights: ['Wayanad Origin', 'High Piperine', 'Sun Dried', 'Hand Picked']
  },
  {
    id: 13,
    name: 'Palm Jaggery',
    category: 'Local Sweets',
    brand: 'Grama Fresh',
    price: 160,
    originalPrice: 210,
    image: '/ai_images/organic_grains_1776231059575.png',
    rating: 4.7,
    reviews: 134,
    tags: ['organic-special'],
    description: 'Handmade palm jaggery (karupatti) from palmyra palm sap, slow-cooked in iron kadai by traditional artisans. Low glycemic index, rich in vitamins B and minerals. A healthier alternative to refined sugar.',
    variants: [
      { id: 35, name: '250g', price: 90 },
      { id: 36, name: '500g', price: 160 },
      { id: 37, name: '1kg', price: 300 },
    ],
    highlights: ['Palmyra Palm', 'Low GI', 'Handmade', 'Iron Kadai Cooked']
  },
  {
    id: 14,
    name: 'Sesame Oil (Nallennai)',
    category: 'Organic Oils',
    brand: 'Namma Nature',
    price: 350,
    originalPrice: 430,
    image: '/ai_images/indian_spices_1776231045209.png',
    rating: 4.8,
    reviews: 201,
    tags: ['best-selling'],
    description: 'Traditional marachekku (wood-pressed) gingelly oil made from black sesame seeds. Rich nutty aroma, dark amber colour. Used in South Indian cooking, Ayurvedic massage (abhyanga) and temple rituals.',
    variants: [
      { id: 38, name: '500ml', price: 350 },
      { id: 39, name: '1L', price: 650 },
      { id: 40, name: '5L', price: 3100 },
    ],
    highlights: ['Marachekku Method', 'Black Sesame', 'Ayurvedic Grade', 'Traditional Recipe']
  },
  {
    id: 15,
    name: 'Barnyard Millet',
    category: 'Grains & Pulses',
    brand: 'Namma Nature',
    price: 120,
    originalPrice: 160,
    image: '/ai_images/organic_grains_1776231059575.png',
    rating: 4.5,
    reviews: 78,
    tags: ['organic-special'],
    description: 'Kuthiraivali (barnyard millet) is one of the most nutritious ancient grains of India. Gluten-free, low carb, and rich in fibre. Perfect substitute for rice during fasting days and for those managing diabetes.',
    variants: [
      { id: 41, name: '500g', price: 120 },
      { id: 42, name: '1kg', price: 220 },
    ],
    highlights: ['Gluten Free', 'Low Carb', 'Ancient Grain', 'Diabetic Friendly']
  },
  {
    id: 16,
    name: 'Organic Coriander Powder',
    category: 'Authentic Spices',
    brand: 'Kovil Kalai',
    price: 70,
    originalPrice: 95,
    image: '/product_coriander_powder.png',
    rating: 4.6,
    reviews: 145,
    tags: ['best-selling'],
    description: 'Sun-dried Rajasthani dhaniya, roasted lightly and stone-ground for a fragrant, citrusy coriander powder. Essential base spice for gravies, sambar, rasam and chutneys. Zero additives, 100% pure.',
    variants: [
      { id: 43, name: '100g', price: 35 },
      { id: 44, name: '250g', price: 70 },
      { id: 45, name: '500g', price: 130 },
    ],
    highlights: ['Stone Ground', 'Rajasthani Origin', 'No Additives', 'Aromatic & Fresh']
  },
  {
    id: 17,
    name: 'Traditional Kai Murukku',
    category: 'Indian Snacks',
    brand: 'Namma Nature',
    price: 145,
    originalPrice: 180,
    image: '/ai_images/murukku_premium.png',
    rating: 4.9,
    reviews: 58,
    tags: ['best-selling', 'organic-special'],
    description: 'Authentic handmade Kai Murukku from Chettinad, crafted with precise hand-rotation. Made using premium rice flour and pure butter, fried in cold-pressed groundnut oil for that perfect traditional crunch.',
    variants: [
      { id: 46, name: '250g', price: 145 },
      { id: 47, name: '500g', price: 280 },
    ],
    highlights: ['Hand-Twisted', 'Butter-Infused', 'Zero Preservatives', 'Chettinad Special']
  },
  {
    id: 18,
    name: 'Spicy Vadu Mango Pickle',
    category: 'Pickles & Pastes',
    brand: 'Grama Fresh',
    price: 195,
    originalPrice: 240,
    image: '/ai_images/mango_pickle_jar.png',
    rating: 4.9,
    reviews: 124,
    tags: ['best-selling'],
    description: 'Baby mangoes (Vadu) curated with traditional spices and cold-pressed sesame oil. This pickle follows a secret 50-year-old family recipe, ensuring the tiny mangoes stay crunchy and absorb the intense spices.',
    variants: [
      { id: 48, name: '250g', price: 195 },
      { id: 49, name: '500g', price: 370 },
    ],
    highlights: ['Small-Batch', 'Cold-Pressed Sesame Oil', 'Authentic Vadu', 'No Vinegar']
  },
  {
    id: 19,
    name: 'Grandma\'s Mysore Pak',
    category: 'Local Sweets',
    brand: 'Kovil Kalai',
    price: 240,
    originalPrice: 300,
    image: '/ai_images/mysore_pak_brass.png',
    rating: 5.0,
    reviews: 89,
    tags: ['best-selling', 'organic-special'],
    description: 'The royal texture of Mysore Pak, made with pure desi cow ghee, fine gram flour, and organic cane sugar. It melts instantly in your mouth, carrying the nostalgia of traditional festive celebrations.',
    variants: [
      { id: 50, name: '250g', price: 240 },
      { id: 51, name: '500g', price: 460 },
    ],
    highlights: ['Pure Desi Ghee', 'Cane Sugar', 'Silk-Soft Texture', 'Handmade']
  },
  {
    id: 20,
    name: 'Mango Ginger Pickle',
    category: 'Pickles & Pastes',
    brand: 'Namma Nature',
    price: 150,
    originalPrice: 180,
    image: '/ai_images/mango_ginger_pickle.png',
    rating: 4.8,
    reviews: 45,
    tags: ['new'],
    description: 'A unique and healthy pickle made from Mango Ginger (Ma-Inji). It has the flavor of raw mango and the health benefits of ginger.',
    variants: [{ id: 52, name: '250g', price: 150 }, { id: 53, name: '500g', price: 280 }],
    highlights: ['Healthy Mango Ginger', 'No Artificial Colors', 'Traditional Recipe']
  },
  {
    id: 21,
    name: 'Authentic Sambar Powder',
    category: 'Authentic Spices',
    brand: 'Kovil Kalai',
    price: 110,
    originalPrice: 135,
    image: '/ai_images/sambar_powder.png',
    rating: 4.9,
    reviews: 156,
    tags: ['best-selling'],
    description: 'Crafted with a blend of hand-picked spices, this Sambar powder brings the authentic taste of South India to your kitchen.',
    variants: [{ id: 54, name: '100g', price: 60 }, { id: 55, name: '250g', price: 110 }],
    highlights: ['Aromatic Blend', 'Stone Ground', 'Preservative Free']
  },
  {
    id: 22,
    name: 'Thin & Crispy Potato Chips',
    category: 'Indian Snacks',
    brand: 'Grama Fresh',
    price: 65,
    originalPrice: 85,
    image: '/ai_images/murukku_premium.png',
    rating: 4.7,
    reviews: 98,
    tags: ['new'],
    description: 'Classic salted potato chips, sliced thin and fried to perfection. The perfect crunchy snack for any time.',
    variants: [{ id: 56, name: '100g', price: 65 }, { id: 57, name: '250g', price: 150 }],
    highlights: ['Ultra Thin', 'Lightly Salted', 'Handmade Style']
  },
  {
    id: 23,
    name: 'Traditional Adhirasam',
    category: 'Local Sweets',
    brand: 'Kovil Kalai',
    price: 180,
    originalPrice: 220,
    image: '/ai_images/mysore_pak_brass.png',
    rating: 4.9,
    reviews: 74,
    tags: ['organic-special'],
    description: 'A classic South Indian sweet made with rice flour and jaggery. Deep-fried to a perfect chewy texture.',
    variants: [{ id: 58, name: '250g', price: 180 }, { id: 59, name: '500g', price: 340 }],
    highlights: ['Jaggery Based', 'Traditional Festival Sweet', 'Handmade']
  },
  {
    id: 24,
    name: 'Fried Gram (Pottu Kadalai)',
    category: 'Grains & Pulses',
    brand: 'Namma Nature',
    price: 45,
    originalPrice: 55,
    image: '/ai_images/organic_grains_1776231059575.png',
    rating: 4.6,
    reviews: 112,
    tags: [],
    description: 'High-quality roasted gram, perfect for making chutneys or as a healthy snack.',
    variants: [{ id: 60, name: '250g', price: 45 }, { id: 61, name: '500g', price: 85 }],
    highlights: ['High Protein', 'Crunchy Texture', 'Versatile Ingredient']
  },
  {
    id: 25,
    name: 'Organic Moong Dal',
    category: 'Grains & Pulses',
    brand: 'Namma Nature',
    price: 130,
    originalPrice: 160,
    image: '/ai_images/organic_grains_1776231059575.png',
    rating: 4.8,
    reviews: 89,
    tags: ['organic-special'],
    description: 'Split yellow moong dal, easy to digest and rich in nutrients. Perfect for khichdi and dal.',
    variants: [{ id: 62, name: '500g', price: 130 }, { id: 63, name: '1kg', price: 250 }],
    highlights: ['Certified Organic', 'Easy to Digest', 'Nutrient Rich']
  },
  {
    id: 26,
    name: 'Garlic Karasev',
    category: 'Indian Snacks',
    brand: 'Namma Nature',
    price: 90,
    originalPrice: 110,
    image: '/ai_images/murukku_premium.png',
    rating: 4.7,
    reviews: 142,
    tags: ['best-selling'],
    description: 'Spicy and crunchy gram flour sticks infused with the bold flavor of fresh garlic.',
    variants: [{ id: 64, name: '200g', price: 90 }, { id: 65, name: '500g', price: 210 }],
    highlights: ['Bold Garlic Flavor', 'Spicy & Crunchy', 'Tea-time Favorite']
  },
  {
    id: 27,
    name: 'Dry Ginger Powder',
    category: 'Authentic Spices',
    brand: 'Kovil Kalai',
    price: 85,
    originalPrice: 105,
    image: '/ai_images/indian_spices_1776231045209.png',
    rating: 4.8,
    reviews: 67,
    tags: [],
    description: 'Finely ground dry ginger (Sukku) powder. Great for tea, cooking, and Ayurvedic benefits.',
    variants: [{ id: 66, name: '100g', price: 85 }],
    highlights: ['Pure Dry Ginger', 'Digestive Benefits', 'Strong Aroma']
  },
  {
    id: 28,
    name: 'Organic Cumin Seeds',
    category: 'Authentic Spices',
    brand: 'Grama Fresh',
    price: 120,
    originalPrice: 150,
    image: '/ai_images/indian_spices_1776231045209.png',
    rating: 4.7,
    reviews: 134,
    tags: ['best-selling'],
    description: 'Highly aromatic organic cumin seeds (Jeera) sourced from Rajasthan.',
    variants: [{ id: 67, name: '100g', price: 65 }, { id: 68, name: '250g', price: 120 }],
    highlights: ['High Oil Content', 'Aromatic', 'Pesticide Free']
  },
  {
    id: 29,
    name: 'Premium Karupatti (Palm Jaggery)',
    category: 'Local Sweets',
    brand: 'Grama Fresh',
    price: 190,
    originalPrice: 240,
    image: '/ai_images/organic_grains_1776231059575.png',
    rating: 4.9,
    reviews: 210,
    tags: ['best-selling', 'organic-special'],
    description: 'Pure palm jaggery, rich in minerals and a great substitute for white sugar.',
    variants: [{ id: 69, name: '250g', price: 100 }, { id: 70, name: '500g', price: 190 }],
    highlights: ['Unrefined', 'Mineral Rich', 'Natural Sweetener']
  },
  {
    id: 30,
    name: 'Wood Pressed Mustard Oil',
    category: 'Organic Oils',
    brand: 'Namma Nature',
    price: 240,
    originalPrice: 299,
    image: '/ai_images/organic_oils_banner.png',
    rating: 4.8,
    reviews: 56,
    tags: ['new'],
    description: 'Pungent and pure wood-pressed mustard oil, retaining all its natural properties.',
    variants: [{ id: 71, name: '500ml', price: 130 }, { id: 72, name: '1L', price: 240 }],
    highlights: ['Cold Pressed', 'Strong Pungency', 'Rich in Omega-3']
  },
];

export const ORDERS = [
  { id: '#ORD-7812', customer: 'Rahul Sharma', status: 'Delivered', amount: '₹1,240', date: '2 mins ago', items: 3 },
  { id: '#ORD-7811', customer: 'Priya Singh', status: 'Processing', amount: '₹850', date: '15 mins ago', items: 1 },
  { id: '#ORD-7810', customer: 'Ankit Kumar', status: 'Pending', amount: '₹420', date: '1 hour ago', items: 4 },
  { id: '#ORD-7809', customer: 'Sita Devi', status: 'Shipped', amount: '₹1,560', date: '3 hours ago', items: 2 },
];

export const PROMOTIONS = [
  {
    id: 1,
    title: 'Summer Sale',
    discount: '20% OFF',
    category: 'All Grains & Pulses',
    end: 'Ends in 3 days',
    active: true,
    code: 'Product20',
    description: 'Get 20% off on all grains and pulses. Stock up now before the season ends.',
    image: '/ai_images/cinematic_farm_1776230966841.png',
    color: '#d97706'
  },
  {
    id: 2,
    title: 'New User Discount',
    discount: 'Flat ₹100 OFF',
    category: 'First Order',
    end: 'Perpetual',
    active: true,
    code: 'WELCOME100',
    description: 'First time shopping with us? Enjoy ₹100 off on your very first order.',
    image: '/ai_images/honey_gold_1776231080758.png',
    color: '#065f46'
  },
  {
    id: 3,
    title: 'Festival Bonanza',
    discount: 'Buy 1 Get 1',
    category: 'Sweets & Snacks',
    end: 'Starts Apr 10',
    active: false,
    code: 'BOGO2026',
    description: 'Double the joy this festival season! Buy one get one free on all sweets and snacks.',
    image: '/ai_images/organic_grains_1776231059575.png',
    color: '#7c3aed'
  },
  {
    id: 4,
    title: 'Fresh Oil Friday',
    discount: '15% OFF',
    category: 'Organic Oils',
    end: 'Every Friday',
    active: true,
    code: 'OILFRIDAY',
    description: 'Every Friday is Oil Friday! Score 15% off all cold-pressed and wood-pressed oils.',
    image: '/ai_images/indian_spices_1776231045209.png',
    color: '#b45309'
  },
];
