type User @table {
  username: String!
  createdAt: Timestamp!
  email: String
  lastLogin: Timestamp
}

type Test @table {
  name: String!
  createdAt: Timestamp!
  testScript: String!
  description: String
  lastRunAt: Timestamp
  user: User
}

type TestRun @table {
  runAt: Timestamp!
  status: String!
  outputLogs: String
  duration: Float
  user: User
  test: Test
}